#!/bin/bash

#13123

tac clamscan_master038.log | while read line

do
    if [ "$line" != "-------------------------------------------------------------------------------" ]; then
        if [ "$out" = 1 ]; then
            check=${line:0:4}
            if [ "$check" = "/var" ]; then


                varee=$(echo $line | cut -d '/' -f 6)
                for i in $varee
                do
                    echo $line | grep $i
                    echo "---------------------------"
                done


            fi
        fi
    else
        if [ "$out" = 1 ]; then
            break
        fi
        out=1
    fi
done
#echo "${log[0]}"